-- CREATE DATABASE

CREATE DATABASE IF NOT EXISTS HANYANG;

-- CREATE TABLE

CREATE TABLE IF NOT EXISTS YTC_MEMBER (
  MEMBER_ID VARCHAR(100) PRIMARY KEY NOT NULL ,
  MEMBER_PW VARCHAR(100),
  MEMBER_NAME VARCHAR(20),
  MEMBER_DATE DATE
);
CREATE TABLE IF NOT EXISTS YTC_VIDEO (
  VIDEO_UUID VARCHAR(100) PRIMARY KEY NOT NULL,
  VIDEO_OWNER VARCHAR(20),
  VIDEO_DIR VARCHAR(100),
  PICTURE_DIR VARCHAR(100),
  VIDEO_DATE DATE,
  VIDEO_VIEWS INT,
  VIDEO_INTRO VARCHAR(1000),
  FOREIGN KEY(VIDEO_OWNER) REFERENCES YTC_MEMBER(MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS YTC_COMMENT(
    COM_ID INT PRIMARY KEY NOT NULL,
    COM_VIDEO_UUID VARCHAR(100) NOT NULL,
    COM_OWNER VARCHAR(100),
    COM_COMMENT VARCHAR(1000),
    FOREIGN KEY(COM_VIDEO_UUID) REFERENCES YTC_VIDEO(VIDEO_UUID),
    FOREIGN KEY(COM_OWNER) REFERENCES YTC_MEMBER(MEMBER_ID)
);

CREATE TABLE IF NOT EXISTS YTC_RECOMMENT (
    RECOM_ID INT PRIMARY KEY NOT NULL,
    RECOM_COM_ID INT,
    RECOM_OWNER VARCHAR(100) NOT NULL,
    RECOM_COMMENT VARCHAR(1000),
	
    FOREIGN KEY(RECOM_COM_ID) REFERENCES YTC_COMMENT(COM_ID),
    FOREIGN KEY(RECOM_OWNER) REFERENCES YTC_MEMBER(MEMBER_ID)
);


-- CREATE SEQUENCE
CREATE SEQUENCE IF NOT EXISTS COMMENT_SEQ START WITH 1 INCREMENT BY 1;


CREATE SEQUENCE IF NOT EXISTS VIDEOVIEW_SEQ START WITH 1 INCREMENT BY 1;
